### ISSUE TITLE
Add support for visualizing schedules

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/wayfinder#123]
# User story

As a transit rider planning on riding the bus tomorrow,
I want to see the full schedule for future dates,
so that I can have confidence of knowing when my bus is supposed to arrive

# Acceptance criteria

- [x] Add a "View Schedule" link to the StopPane that navigates to a new webpage: `/stops/:stop_id/schedule`
- [x] Add a Schedule page that essentially duplicates the features found on the current schedule page: https://app.staging.sound.obaweb.org/where/schedule?id=1_280#route_1_100104
- [x] Show a date picker via a "Show Calendar" button or dropdown (or whatever) that mirrors the behavior of the current page
- [x] A header that includes the name of the stop, its ID, direction, current date, and a link to the stop page for real time information: `/stops/:stop_id`
- [x] An [accordion](https://flowbite-svelte.com/docs/components/accordion) that shows all available routes at the stop 
- [x] Include two buttons above the accordion: Show all Routes and Collapse all Routes, which expand and collapse all accordion items respectively.
- [x] A replica(?) of the table UI that shows the schedule of each route. If it's possible to duplicate the "To highlight specific trips" feature, then let's definitely include that too.

**Comment by petedussin** [comment]
Ex: https://app.staging.sound.obaweb.org/where/schedule?id=40_N17-T2

**Comment by aaronbrethorst** [comment]
support for printing

**Comment by aaronbrethorst** [comment]
point to point schedule is popular: https://www.soundtransit.org/ride-with-us/routes-schedules/1-line?at=1731621597103&direction=0&start_stop=null&view=table&route_tab=schedule&stops_0=40_N23%2C40_S01&stops_1=40_S01%2C40_N23
