### ISSUE TITLE
DRAFT: Point to point schedule

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/wayfinder#125]
This needs more work before we can implement, but this is apparently a very popular feature with ST riders. Maybe we can build something similar.

https://www.soundtransit.org/ride-with-us/routes-schedules/1-line?at=1731621597103&direction=0&start_stop=null&view=table&route_tab=schedule&stops_0=40_N23%2C40_S01&stops_1=40_S01%2C40_N23

**Comment by petedussin** [comment]
@aaronbrethorst I'm sorry, I was a little flip about the popularity of point-to-point schedules, I'm not really sure of its popularity, we should discuss. It was mostly top of mind because it was used as the basis of a couple of complaints recently about bus service...
