### ISSUE TITLE
Duplicate Scrollbars When Viewing Trip Details in StopPane Modal 

### ISSUE THREAD

**Issue by Ahmedhossamdev** [OneBusAway/wayfinder#128]
### Description  

When opening the `stopPane` modal and then the `tripDetails` modal:  

- Two scrollbars appear in the `tripDetailsModal` and `arrivalsAndDepartures` sections.  

- The `arrivalsAndDepartures` section in the `stopPane` modal remains open. It should be closed automatically when the `tripDetails` modal is opened.  

- Additionally, we need to handle the case when the `stopPane` is used outside the `modalPane`. In this case:  
  - The inner scroll should be activated for the `stopPane`.  
  - When the `stopPane` is used within the `modalPane`, the scroll should be disabled to prevent redundant scrollbars.  

### Steps to Fix  

- Remove the `overflow-y-auto` and `scroll` from the `arrivalsAndDepartures` and `tripDetailsModal`, as the `modalPane` already contains `overflow-y-auto`.  

- Implement logic to conditionally enable or disable the inner scroll for the `stopPane`:  
  - Enable inner scroll when `stopPane` is used outside `modalPane`.  
  - Disable inner scroll when `stopPane` is used within `modalPane`. 

![image](https://github.com/user-attachments/assets/9d5719ff-2867-417d-839d-dcd0021fecd0)

**Comment by aaronbrethorst** [comment]
I think this is best fixed with the draft PR I have opened: #129 - can you finish that up with the new accordion style UI for the trip details pane?

**Comment by Ahmedhossamdev** [comment]
Great
