### ISSUE TITLE
Add feature to "View All Routes"

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/wayfinder#64]
The current enterprise webapp has a "View All Routes" feature that we should replicate. 

Check out https://bustime.mta.info and click on the link under "[Click here](https://bustime.mta.info/routes) for a list of available routes."

For our purposes, clicking on the link should open a modal pane containing this content. The content should be cached on first load so that subsequent loads don't take long. The UI of the https://bustime.mta.info/routes/ page's routes list should be mimicked, more or less.

The View All Routes modal pane should have a search box at the top of it that does real-time matching against the results on the page.

**Comment by Ahmedhossamdev** [comment]
#70
