### ISSUE TITLE
Show locations of buses in realtime when a route is selected

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/wayfinder#65]
See here for instance: https://bustime.mta.info/#B1

For now, let's just match the UI, both in terms of showing the direction of travel and the popup that appears when clicking on a bus.

Also, bus locations should be updated every 30 seconds.

<img width="409" alt="image" src="https://github.com/user-attachments/assets/2a1a6838-61ce-4c4d-b593-d48046f3343c">

**Comment by Ahmedhossamdev** [comment]
#69
