### ISSUE TITLE
Make sure that directional arrows on stop icons are shown at cardinal directions

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/wayfinder#87]
it looks like our directional arrows are slightly off from N, NE, E, SE, S, SW, W, and NW:

<img width="399" alt="image" src="https://github.com/user-attachments/assets/9aff303c-2e6b-4626-b5ae-40318b11973d">

**Comment by Ahmedhossamdev** [comment]
Fixed here: #95
