### ISSUE TITLE
Arrival and Departure Data Not Updating in Modal When Selecting Another Stop

### ISSUE THREAD

**Issue by Ahmedhossamdev** [OneBusAway/wayfinder#93]
https://github.com/user-attachments/assets/1ceff57f-e6ad-4ca0-9152-c61aa981e69a

**Comment by tarunsinghofficial** [comment]
Hi @Ahmedhossamdev,

It's not a bug, but we haven't implemented that feature yet. Currently, it works by only closing one stop and opening another :)

**Comment by Ahmedhossamdev** [comment]
Hey @tarunsinghofficial 

Cool, thanks for the clarification. I had no idea that it was not implemented, but as a user, I will notice that something went wrong, so I will add it as an issue.
